### ISSUE TITLE
Front page redirects to wrong URL (404)

### ISSUE THREAD

**Issue by seanh** [hypothesis/via3#194]
If you visit http://localhost:9083/ and paste in a URL it'll redirect you to http://localhost:9083/http://example.com which is a 404. It should be http://localhost:9083/route?url=http://example.com

See also:

* https://github.com/hypothesis/via3/issues/40 (another bug with the front page)

**Comment by jon-betts** [comment]
@seanh Are you sure about this one? It redirects to 9080 for me, which is original Via. Could you try and intercept the call being made by the form. It's a single named field (url), so I can't really see how it could not result in sending you to the route URL above that is working?

**Comment by robertknight** [comment]
This issue is no longer applicable. Entering a URL on the home page still redirects to `/<URL>` but that is no longer a 404. Instead the URL is proxied as with legacy Via.
