### ISSUE TITLE
Improve debug-ability of PDF proxying errors

### ISSUE THREAD

**Issue by robertknight** [hypothesis/via3#356]
On Friday 2021-02-01 @mattdricker [notified us](https://hypothes-is.slack.com/archives/C4K6M7P5E/p1612200810247600) of many reports from users about assignments using PDFs from Google Drive failing to load. The behavior seen by users was that the PDF.js viewer application loaded in Via but the PDF itself failed to load, with PDF.js displaying the following error:

```
Message: Unexpected server response (400) while retrieving PDF
```

[Longer version with more details](https://hypothes-is.slack.com/archives/C4K6M7P5E/p1612200905248100?thread_ts=1612200810.247600&cid=C4K6M7P5E).

We were able to reproduce the problem but it took some time to debug because the error response was a completely generic 400 nginx error which could have been coming from one of several nginx instances involved in processing the request. It eventually turned out that the 400 error response was a result of the real error from the Google Drive API [being masked](https://github.com/hypothesis/via3/blob/d154c0fd2ef065c8cfac059c7fe332874f297502/conf/nginx/includes/errors.conf#L36) by the nginx proxy that Via 3 runs. 

The real error was a 403 response for requests to the `https://www.googleapis.com/drive/v3/files/{id}` endpoint with a body that included the text:

```
Your computer or network may be sending automated queries. To protect our users, we can't process your request right now.
```

Tracking this down was further complicated by the fact that whether this request succeeded or failed depended on various attributes of the request, as seen by Google, which are opaque to us. Issuing the same request directly using curl, even from a production Via 3 Docker container, did not reproduce the issue.

@indigobravo mentioned a [change to the Google Drive / Picker API](https://cloud.google.com/blog/products/application-development/upcoming-changes-to-the-google-drive-api-and-google-picker-api) which he thought may have been related. This is being tracked in https://github.com/hypothesis/via3/issues/405

We hadn't made any recent changes to the way that Via 3 uses the Google Drive API, but we had made some operational changes which resulted in the requests coming from a different and smaller range of IPs. The immediate fix taken that evening was to revert these changes, resulting in requests from Via to Google Drive coming from a larger range of IPs.

## Action items

- [ ] Make similar problems easier to debug in future by making sure we have a way to easily determine a) that an error happened in the upstream request for the PDF and b) what the original HTTP status code was. It would be nice to be able to get the original body as well, but this is less critical.

**Comment by jon-betts** [comment]
I have a task to add a ticket about sorting out the Google Drive mechanism (point two). I'd say that's pretty crucial as even with our fix at the moment we are basically reset to before we attempted to fix this in the first place. We know it wasn't enough then, and I don't think it'll be enough now. My guess is pretty soon we are going to hover back over the line that gets us blocked.

Getting the original body _by default_ might not be a very good idea without doing something fancy. Replacing a log line with the contents of any page could increase the log length arbitrarily or have a high performance cost. Although it might be nice if:

* We could keep them separately in a much more frequently rotated file
* We could turn it on temporarily on demand
* We could sample them or something, rather than keep the lot?

**Comment by seanh** [comment]
I think I closed this by accident

**Comment by jon-betts** [comment]
I've scoped this ticket down to just debugging stuff and move the fixing it off to: https://github.com/hypothesis/via3/issues/405

**Comment by seanh** [comment]
Slack discussion: https://hypothes-is.slack.com/archives/C1MA4E9B9/p1616763370094600

**Comment by seanh** [comment]
We've [decided to punt on this for now](https://hypothes-is.slack.com/archives/C1MA4E9B9/p1616763370094600)
