### ISSUE TITLE
PDF annotations have incorrect `target_uri`

### ISSUE THREAD

**Issue by esanzgar** [hypothesis/via3#372]
**Update (2021-03-19): via3.hypothes.is was replaced by via4.hypothes.is. The issue of annotations having the wrong `target_uri` when annotated through Via persists. See [comment](https://github.com/hypothesis/via3/issues/372#issuecomment-802622990) - @robertknight**

I found mentions of via3 URL in the `target_uri` in the annotation table. This happens mostly for PDF, for example, `https://via3.hypothes.is/proxy/static/https://whc.unesco.org/archive/convention-en.pdf`

Ideally the `https://via3.hypothes.is/proxy/static/` shouldn’t be there.

A few more examples of these URL can be retrieved using this SQL query:  `select * from document_uri where claimant ~'via3';`

## Steps to reproduce

1. Go https://hypothesis.instructure.com/courses/125/assignments/878
2. Add an annotations

## Expected result

`target_uri` should be `https://h.readthedocs.io/_/downloads/en/latest/pdf/`

## Actual result

`target_uri` is `https://qa-via3.hypothes.is/proxy/static/fApI11LAAE8wQAJpdjyVJQ/1613066400/https://h.readthedocs.io/_/downloads/en/latest/pdf`

## Additional information

This issue also involves to the client and h. The client uses `document.location.href` as the target of the annotation. For PDF downloads this is the whole URL.

If there would be a way to eliminate the via3 portion when creating annotation it would mean that one could find annotations either in:

- `https://via3.hypothes.is/proxy/static/https://whc.unesco.org/archive/convention-en.pdf`, or
- `https://whc.unesco.org/archive/convention-en.pdf`

## Possible solutions

- The client strips the via3 portion of the URL. This is not very clean.
- Strip the via3 portion of the URL on the backend. Not very clean neither.
- I have heard there is some sort of unique signature on a PDF. Could that be a solution?

## Warning

Whatever we do, it should be backward compatible. People should be able to find their old annotations, even thought they were included using a different URL.

**Comment by robertknight** [comment]
I believe it is this issue that is causing the Notebook to display the wrong document information:

<img width="688" alt="Notebook PDF metadata" src="https://user-images.githubusercontent.com/2458/111746727-4fc15e80-8886-11eb-9836-ec760ce7353d.png">

**Comment by robertknight** [comment]
I'm 95% sure legacy Via did not have this problem, so there was some solution in place for that service. We need to figure out why it is not applied to Via 3. The issue may not be in Via itself.

When we come to address this, we should split resolving the issue for existing annotations and resolving it for new ones into separate tasks.

**Comment by esanzgar** [comment]
`h` has some logic to remove the proxy portion from the URLs:
https://github.com/hypothesis/h/blob/ce07b5247dd177bf5162e8019c120233e4600687/h/util/uri.py#L148-L152

I wonder if it should be updated to reflect the new family of proxy URLs?

**Comment by robertknight** [comment]
It looks to me like Via3 is passing the wrong URL to PDF.js in its configuration: https://github.com/hypothesis/via3/blob/130ff9650f6dcd1d7fb5516c562fc02a217e9c71/via/static/js/pdfjs-init.js#L80

Note that `url` (the proxied PDF URL) is passed as both the URL to load and the original URL that `PDFViewerApplication.url` should return.

**Comment by robertknight** [comment]
https://github.com/hypothesis/via3/pull/427 fixed the issue for new annotations. It will not however fix the issue for existing annotations that have already been made using Via 3.
