### ISSUE TITLE
Investigate if changes to Google Drive auth are required

### ISSUE THREAD

**Issue by jon-betts** [hypothesis/via3#405]
There was an outage detailed in https://github.com/hypothesis/via3/issues/356  which was caused by sending too many request for Google docs like this:

`https://www.googleapis.com/drive/v3/files/{id}`

We were getting errors saying:

> Your computer or network may be sending automated queries. To protect our users, we can't process your request right now.

This is weird as the API end-point above is explicitly for automated queries. @indigobravo mentioned [a change to the Google Drive / Picker API](https://cloud.google.com/blog/products/application-development/upcoming-changes-to-the-google-drive-api-and-google-picker-api) which he thought may have been related:

> First, we’re making changes to authorization for the Google Drive API. If you authorize download requests to the Drive API using the access token in a query parameter, you will need to migrate your requests to authenticate using an HTTP header instead. Starting January 1, 2020, download calls to files.get, revisions.get and files.export endpoints which authenticate using the access token in the query parameter will no longer be supported, which means you’ll need to update your authentication method.

It looks like this means our request to the API are counted as user requests and subject to much lower limits than automated requests.

# Implementation notes

* Oh no, this looks like we need a full OAuth 2 flow if we want do do this
* This probably means not doing it with NGINX

# Things to do

- [ ] Investigate whether the mechanism used to [authenticate requests to the Google Drive API](https://github.com/hypothesis/via3/blob/d154c0fd2ef065c8cfac059c7fe332874f297502/conf/nginx/includes/direct_proxy.conf#L16) needs to be changed on the basis of https://cloud.google.com/blog/products/application-development/upcoming-changes-to-the-google-drive-api-and-google-picker-api
- [ ] Decide whether we want to re-apply [the changes](https://github.com/hypothesis/deployment/pull/178) that were reverted in order to fix the issue

**Comment by jon-betts** [comment]
Some random observations from discussions in Slack and poking about.

## This probably has nothing to do with how we are authenticating

We're not the only people getting this:

* https://stackoverflow.com/questions/62367007/google-drive-api-computer-or-network-may-be-sending-automated-queries-requesti
* https://stackoverflow.com/questions/60700981/google-drive-api-response-but-your-computer-or-network-may-be-sending-automated
* https://issuetracker.google.com/issues/153717392
* https://issuetracker.google.com/issues/152898913

There are no useful answers there, but the first one very closely mirrors our experience and access method. The second is using OAuth 2.0 and hitting the same issue. The second even mentions that this started "in recent months".

## We might be able to avoid this entirely

We use this URL in two different ways:

* From the back-end to get the content and see why type it is (is this a PDF?)
* From the template where we load PDF.js to actually display it

When we come from LMS we assume that all Google documents are PDFs and skip the routing step. We could (might already?) do the same thing internally.

In the case of the second we may be able to load the PDF directly without running into any CORS issues. This would leave every individual user as the one encountering any blocking. As they are individuals, it's likely that any Google fingerprinting stuff would let them access the document.

## How we are authenticating might stop working though...

The docs state:

> Starting January 1, 2020, download calls to files.get, revisions.get and files.export endpoints which authenticate using the access token in the query parameter will no longer be supported, which means you’ll need to update your authentication method.

There's a bit more gap in this statement than there might first appear to be. It says this isn't "supported" but it doesn't say it won't work. It says "you'll need to update", but it doesn't say when. Reading between the lines and some of the bug reports, I think this might mean it's "deprecated/discouraged" for now and make come into absolute force at a point undetermined in the future.

If the above plan works out, this might not be an issue at all.

**Comment by jon-betts** [comment]
Looks like we are probably looking for a service account:

 * https://developers.google.com/identity/protocols/oauth2/service-account
 
If we do that we might also be able skip all the OAuth madness by using a JWT: https://developers.google.com/identity/protocols/oauth2/service-account#jwt-auth.

Seems like JWT is a no go according to this: https://stackoverflow.com/questions/60343139/is-it-possible-to-do-authorized-calls-to-google-drive-api-using-a-signed-jwt, but it does give examples of using a service account.

Details of the Python class used in that example: https://github.com/googleapis/google-api-python-client/blob/master/docs/README.md, specifically https://googleapis.github.io/google-api-python-client/docs/dyn/drive_v3.html

**Comment by jon-betts** [comment]
From what I can see here doing the "correct" thing here still gets you kicked to the curb after you go above about 100 requests.

Although we are hitting a more informative API style error: 

```
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://www.googleapis.com/drive/v3/files/1RMhWqrquganFpkmj4f9Nl107HsMp85U1?alt=media returned "User Rate Limit Exceeded. Rate of requests for user exceed configured project quota. You may consider re-evaluating expected per-user traffic to the API and adjust project quota limits accordingly. You may monitor aggregate quota usage and adjust limits in the API Console: https://console.developers.google.com/apis/api/drive.googleapis.com/quotas?project=132712752872". Details: "User Rate Limit Exceeded. Rate of requests for user exceed configured project quota. You may consider re-evaluating expected per-user traffic to the API and adjust project quota limits accordingly. You may monitor aggregate quota usage and adjust limits in the API Console: https://console.developers.google.com/apis/api/drive.googleapis.com/quotas?project=132712752872">
```

I've signed up for a service account, which I think is "the user". Which makes me wonder... what if you have two?

**Comment by jon-betts** [comment]
Yeah, this is mega dumb. The rate is something like 100/100s per user. So if you go below 1 request per second you don't seem to get blocked. 

I've tried this with three service accounts, and seeing as getting the file takes ~330ms running three workers, I actually can't exceed the limit any more. 

One "solution" to this might be to see what our peak requests per 100s are. Divide that by 100 and then round robin between that many service accounts.

From what I can see, if you have a single set of credentials, the Google code with run through the auth flow for you on them. I can't see how this is going to not fight if we share the account between instances... but maybe we could have enough accounts that every instance gets it's own credential? I've no idea how we'd achieve that.

**Comment by marcospri** [comment]
There's also this edit quota UI here:

https://console.cloud.google.com/iam-admin/quotas?project=via-dev-273714&folder=&organizationId=

But if I understand it correctly it seems to suggest we are at the upper limit quota wise?

![Screenshot from 2021-03-10 10-09-05](https://user-images.githubusercontent.com/1433832/110604787-be1c6780-8188-11eb-99ec-a907e23e9fa7.png)

**Comment by jon-betts** [comment]
As far as I can tell the quota there is just a lie. No matter what you put there you get throttled when you go over about 100 / 100 seconds. We are nowhere near that limit...

**Comment by jon-betts** [comment]
The conclusions of this spike:

* Nothing is certain with Google, it's all guesswork
* We can do two legged OAuth 2 quite easily with the Google libraries
* We seem to hit limits well below the stated quota with service accounts
* Round robining service accounts appears to get a higher total quota
* After enabling billing we appear to have got a much higher single account quota (no idea if this is the cause)
* Our caching is not effective with Google Drive due to `Vary: Origin`, `Vary: X-Origin` headers

Recommendations:

 * Add a new Python end-point to Via 3 which will use the libraries to download Google Drive files
 * Use a single account
 * Emit headers to ensure the results can be cached
 * Keep the old method behind a feature flag or other easily toggled change, so we can roll back if we hit issues

**Comment by jon-betts** [comment]
Follow up ticket here: https://github.com/hypothesis/via3/issues/411
