### ISSUE TITLE
Attempt to upgrade `pyramid_services`

### ISSUE THREAD

**Issue by jon-betts** [hypothesis/via3#429]
For: https://github.com/hypothesis/product-backlog/issues/1199

We should attempt to upgrade `pyramid_services` to as high a version of Python as we can. It's used in many of our products and in particular is holding back the `via3` ugprade.

This is partially to allow a Via 3 upgrade (and others) but also to gain experience working with a 3rd party library and updating it.

**Comment by jon-betts** [comment]
I've tested this locally, and it seems to pass all it's own tests up to version 3.9. The project only lists 3.6 compatibility, so this might be a good candidate for a PR back to the maintainer. I'd say we can safely treat this as working with 3.9 though.

**Comment by marcospri** [comment]
> I've tested this locally, and it seems to pass all it's own tests up to version 3.9. The project only lists 3.6 compatibility, so this might be a good candidate for a PR back to the maintainer. I'd say we can safely treat this as working with 3.9 though.

Are we treating those PR to include the 3.9 in the upstream libraries compatibility list as mandatory? Or we could start upgrading without merging all of those?

**Comment by jon-betts** [comment]
No I don't think so, as we can't really be sure we can even make a PR, let alone that it would be accepted etc.

The epic here as definitions of what we'd accept: https://github.com/hypothesis/product-backlog/issues/1199

Basically it's very nice and convenient if they declare compatibility, but it's only the first (and easiest) way to accept it being true.

**Comment by jon-betts** [comment]
I've made a PR for this here: https://github.com/jon-betts/pyramid_services/pull/1

**Comment by jon-betts** [comment]
The PR upstream is: https://github.com/mmerickel/pyramid_services/pull/15

**Comment by seanh** [comment]
@jon-betts I wonder if we should close this card? The PR isn't merged yet but we've done the work of sending it. I suppose we may still have to respond to some feedback on the PR if/when it comes, but maybe we don't need to keep this card open to remind us of that?

**Comment by jon-betts** [comment]
Yep I think so, I'm tracking these on: hypothesis/product-backlog#1199, in case any follow up is required. Also putting in a working PR answers all the questions we have about compatibility.
